### ISSUE TITLE
DotA

### ISSUE THREAD

**Issue by ph98** [SharifAIChallenge/AIC18-Maps#1]
hi 

in doc_v2 you mentioned that : 

> ‫دارند‪.‬‬ ‫متمایز‬ ‫انتهایی‬ ‫و‬ ‫ابتدایی‬ ‫خانه‬ ‫که‬ ‫هستند‬ ‫نقشه‬ ‫های‬ ‫خانه‬ ‫از‬ ‫پیوسته‬ ‫ای‬ ‫دنباله‬ ‫ها‪:‬‬ ‫جاده‬

but in this map this term not applied :( 
which one is wrong ? the document ? orDotA ?

**Comment by ali-behjati** [comment]
هر دو درست هستند، خانه‌های یک مسیر هیچ وقت تکراری نیست اما خانه‌های دو مسیر
می‌تواند تکراری باشد. همچنین لزومی ندارد اغاز و پایان مسیر بر روی گوشه‌ی
نقشه باشند.

**Comment by ph98** [comment]
واقعا انگلیسی نوشتن سخته :)
من مشکلم با گوشه بودن یا نبودن نیس
اینکه خونه های اول و آخر مسیر متمایز هستن یا نه ؟ 
تو مپ A هر سه مسیر از یه خونه شروع میشن!!!

**Comment by ali-behjati** [comment]
خیر متمایز نیستن، میتونن تکراری باشن و در نتیجه مپ «آ» درسته
